const AllergenGroups = Object.freeze({
  GLUTEN: "GLUTEN",
  CRUSTACEANS: "CRUSTACEANS",
  EGGS: "EGGS",
  FISH: "FISH",
  PEANUTS: "PEANUTS",
  SOY: "SOY",
  DAIRY_PRODUCTS: "DAIRY_PRODUCTS",
  TREE_NUTS: "TREE_NUTS",
  CELERY: "CELERY",
  MUSTARD: "MUSTARD",
  SESAME: "SESAME",
  MOLLUSCS: "MOLLUSCS",
  LUPINS: "LUPINS",
});

module.exports = AllergenGroups;
