const Permissions = Object.freeze({
  DELETEUSER: "DELETEUSER",
  MODIFYUSER: "MODIFYUSER",
  MODIFYALLERGIES: "MODIFYALLERGIES",
  MODIFYPATIENTINFO: "MODIFYPATIENTINFO",
  RECIPEREVIEW: "RECIPEREVIEW",
});

module.exports = Permissions;
