const Permissions = Object.freeze({
  DELETE_USER: "DELETE_USER",
  MODIFY_USER: "MODIFY_USER",
  MODIFY_ALLERGIES: "MODIFY_ALLERGIES",
  MODIFY_PATIENT_INFO: "MODIFY_PATIENT_INFO",
  RECIPE_REVIEW: "RECIPE_REVIEW",
});

module.exports = Permissions;
